### ISSUE TITLE
How to use OD atom type for oxygen atom

### ISSUE THREAD

**Issue by amin-sagar** [darianyang/ff15ipq-19F#2]
Hello.
Thanks for sharing these scripts.
I am trying to parameterize norleucine.
I am following the scripts but I have encountered a problem i.e. if I change the atom type of oxygen atom to OD and run parmchk as follows.
```
parmchk2 -i NLE.mol2 -f mol2 -o NLE.frcmod -p /home/amin/softwares/amber22/dat/leap/parm/parm15ipq_10.3.dat
```
I get an error
```
Atom type of OD does not exist in PARMCHK.DAT
```
If I use atom type O, it works and I get an frcmod file as expected.
Did you encounter this problem as well? 
Can you think of something I might be doing wrong?
The atom section of my mol2 is as follows.
```
@<TRIPOS>ATOM
      1 N           -1.9680     0.0710     0.3120 N          1 NLE      -0.251000
      2 CA          -1.2060     1.2220    -0.1620 CX         1 NLE      -0.054000
      3 C            0.2920     1.0090     0.0910 C          1 NLE       0.216000
      4 O            0.7170     0.4370     1.0960 OD         1 NLE      -0.217000
      5 CB          -1.7010     2.5050     0.5400 2C         1 NLE      -0.190000
      6 CG          -1.3600     3.7940    -0.2280 3C         1 NLE      -0.153000
      7 CD          -1.8050     5.0560     0.5250 CT         1 NLE      -0.159000
      8 CE          -1.6020     6.3320    -0.2980 CT         1 NLE      -0.211000
      9 H           -1.4810    -0.3330     1.1060 H          1 NLE       0.138000
     10 HA          -1.3700     1.3210    -1.2370 H1         1 NLE       0.142000
     11 HB2         -2.7830     2.4620     0.6610 HC         1 NLE       0.095500
     12 HB3         -1.2860     2.5590     1.5490 HC         1 NLE       0.095500
     13 HG2         -1.8470     3.7630    -1.2030 HC         1 NLE       0.084500
     14 HG3         -0.2880     3.8500    -0.4220 HC         1 NLE       0.084500
     15 HD2         -2.8560     4.9750     0.8000 HC         1 NLE       0.079000
     16 HD3         -1.2490     5.1380     1.4590 HC         1 NLE       0.079000
     17 HE1         -1.8950     7.2150     0.2720 HC         1 NLE       0.074000
     18 HE2         -0.5590     6.4580    -0.5890 HC         1 NLE       0.074000
     19 HE3         -2.2040     6.3150    -1.2090 HC         1 NLE       0.074000
```
I would be really grateful for any suggestions.
Best,
Amin.

**Comment by darianyang** [comment]
Hi Amin,

This error feels familiar but I don't remember clearly, and I feel like using the ff15ipq parm file should have prevented it.
I may have manually changed the frcmod after running parmchk using the original amber AT naming. This would be fine to do since the parameters added by the frcmod file are added on top of the parm file, so as long as the lib/frcmod and your mol2 or pdb match it should work.

An important note though, if you're interested in using NLE with the ff15ipq force field, this is already included in the ff15ipq parameters. In fact, this was one of the original motivations for ff15ipq, when attempting to parameterize NLE with ff14ipq, some issues came about that lead the developers to completely update the force field. 

So you could just include a protein with a NLE residue if you source ff15ipq, see line 2569 of $AMBERHOME/dat/leap/lib/amino15ipq_10.0.lib for the correct atom names and types if needed.

Best,
Darian

**Comment by amin-sagar** [comment]
Thanks Darian for your response.
I also asked the question on the Amber mailing list and the developers think that parmchk2 only looks for Amber atom types in parm10.dat even if the -p option is specified.
I am actually using NLE as a test case to make sure I do everything correctly because I have your results to confirm. 
Once I am able to do all the steps with NLE, I will start working with other modified amino acids.
I will use your approach of editing the frcmod file after running parmchk.
I will probably come back with more questions if I encounter errors in the next steps.
Thanks again for your help.
Amin.
